[window]
decorations = "none"  # removes top bar
opacity = 1.0
padding = { x = 10, y = 10 }

[font]
normal = { family = "Fira Code", style = "Regular" }  # Gnome-style font
size = 12.0

[colors.primary]
background = "#000000"
foreground = "#00FF00"  # Green text

[colors.cursor]
text = "CellBackground"
cursor = "#00FF00"

[colors.normal]
black = "#000000"
red = "#800000"
green = "#00FF00"
yellow = "#808000"
blue = "#000080"
magenta = "#800080"
cyan = "#008080"
white = "#C0C0C0"

[colors.bright]
black = "#808080"
red = "#FF0000"
green = "#00FF00"
yellow = "#FFFF00"
blue = "#0000FF"
magenta = "#FF00FF"
cyan = "#00FFFF"
white = "#FFFFFF"
